FROM alpine:3.11

# Install CA certificates
RUN apk add --no-cache --virtual=build-dependencies ca-certificates git

ADD bmrg-auth-proxy /bin/
#RUN 'sh' '-c' 'go get github.com/bitly/oauth2_proxy'

# Expose the ports we need and setup the ENTRYPOINT w/ the default argument
# to be pass in.

USER 2000:2000

EXPOSE 8080 4180
ENTRYPOINT [ "./bin/bmrg-auth-proxy" ]